name: Continuous Integration (JavaScript)

on: [push]

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
  
      - run: |
          dir=$(yarn cache dir)
          ls $dir
  
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - run: ls /home/runner/.cache/yarn/v6

      - name: Run Flow checks
        run: |
          yarn flow version --binary
          yarn run flow --max-warnings=0

      - name: Run Eslint
        run: yarn run lint

      - name: Run Jest tests
        run: yarn run test-only

      - name: Run monorepo scanner
        run: yarn run scanner
